### ISSUE TITLE
java.lang.Exception: KmerHistogramBuilder Failed : 1

### ISSUE THREAD

**Issue by housw** [iychoi/libra#2]
Hi, 

I got an error while trying run libra on my local linux with this command `hadoop jar ~/software/src/libra/libra-all.jar preprocess -k 20 -t 8 -o libra_index input_reads`. Here is the error message:
```
19/01/08 10:04:39 INFO mapred.LocalJobRunner: map > sort
19/01/08 10:04:39 INFO mapred.LocalJobRunner: map > sort
19/01/08 10:04:39 INFO mapred.LocalJobRunner: map > sort
19/01/08 10:04:39 INFO mapred.LocalJobRunner: map > sort
19/01/08 10:04:39 INFO mapreduce.Job: Counters: 18
	File System Counters
		FILE: Number of bytes read=1042463389
		FILE: Number of bytes written=1732141840
		FILE: Number of read operations=0
		FILE: Number of large read operations=0
		FILE: Number of write operations=0
	Map-Reduce Framework
		Map input records=515
		Map output records=178
		Map output bytes=2917776
		Map output materialized bytes=2919556
		Input split bytes=29726
		Combine input records=178
		Combine output records=178
		Spilled Records=178
		Failed Shuffles=0
		Merged Map outputs=0
		GC time elapsed (ms)=80042
		Total committed heap usage (bytes)=95563022336
	File Input Format Counters 
		Bytes Read=532480
19/01/08 10:04:39 INFO mapred.LocalJobRunner: map > sort
19/01/08 10:04:39 ERROR preprocess.Preprocessor: java.lang.Exception: KmerHistogramBuilder Failed : 1
19/01/08 10:04:39 INFO mapred.LocalJobRunner: map > sort
19/01/08 10:04:39 INFO mapred.LocalJobRunner: map > sort
java.lang.Exception: KmerHistogramBuilder Failed : 1
	at libra.preprocess.Preprocessor.run(Preprocessor.java:107)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:76)
	at libra.preprocess.Preprocessor.main(Preprocessor.java:47)
	at libra.Libra.main(Libra.java:74)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:244)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:158)
19/01/08 10:04:39 INFO mapred.LocalJobRunner: map > sort
19/01/08 10:04:39 INFO mapred.LocalJobRunner: map > sort
19/01/08 10:04:39 INFO mapred.LocalJobRunner: map > sort
```
Any idea?

Thanks, 
Shengwei

**Comment by iychoi** [comment]
Hi,

Although I cannot tell you exact reasons of the error without looking at your hadoop setup, I guess the error is realted to low memory. Did you run the Libra on a real Hadoop cluster, or a local pseudo distributed mode? If it is a local pseudo distributed mode, you will suffer such memory-related errors a lot. I do not recommand running the libra on a local setup if the input data is larger than 100MB. Also, the value with -t option means the number of reducer process in this case, so, if you assign 1GB for each reducer tasks, the reducers will consume at least 8GB. This prevents other processes from getting memory for run.

Regards,
Illyoung Choi



보낸 사람: housw
보낸 날짜: 2019년 1월 8일 화요일 오전 11:07
받는 사람: iychoi/libra
참조: Subscribed
제목: [iychoi/libra] java.lang.Exception: KmerHistogramBuilder Failed : 1(#2)

Hi,
I got an error while trying run libra on my local linux with this command hadoop jar ~/software/src/libra/libra-all.jar preprocess -k 20 -t 8 -o libra_index input_reads. Here is the error message:
19/01/08 10:04:39 INFO mapred.LocalJobRunner: map > sort
19/01/08 10:04:39 INFO mapred.LocalJobRunner: map > sort
19/01/08 10:04:39 INFO mapred.LocalJobRunner: map > sort
19/01/08 10:04:39 INFO mapred.LocalJobRunner: map > sort
19/01/08 10:04:39 INFO mapreduce.Job: Counters: 18
	File System Counters
		FILE: Number of bytes read=1042463389
		FILE: Number of bytes written=1732141840
		FILE: Number of read operations=0
		FILE: Number of large read operations=0
		FILE: Number of write operations=0
	Map-Reduce Framework
		Map input records=515
		Map output records=178
		Map output bytes=2917776
		Map output materialized bytes=2919556
		Input split bytes=29726
		Combine input records=178
		Combine output records=178
		Spilled Records=178
		Failed Shuffles=0
		Merged Map outputs=0
		GC time elapsed (ms)=80042
		Total committed heap usage (bytes)=95563022336
	File Input Format Counters 
		Bytes Read=532480
19/01/08 10:04:39 INFO mapred.LocalJobRunner: map > sort
19/01/08 10:04:39 ERROR preprocess.Preprocessor: java.lang.Exception: KmerHistogramBuilder Failed : 1
19/01/08 10:04:39 INFO mapred.LocalJobRunner: map > sort
19/01/08 10:04:39 INFO mapred.LocalJobRunner: map > sort
java.lang.Exception: KmerHistogramBuilder Failed : 1
	at libra.preprocess.Preprocessor.run(Preprocessor.java:107)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:76)
	at libra.preprocess.Preprocessor.main(Preprocessor.java:47)
	at libra.Libra.main(Libra.java:74)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:244)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:158)
19/01/08 10:04:39 INFO mapred.LocalJobRunner: map > sort
19/01/08 10:04:39 INFO mapred.LocalJobRunner: map > sort
19/01/08 10:04:39 INFO mapred.LocalJobRunner: map > sort
Any idea?
Thanks,
Shengwei

**Comment by housw** [comment]
Hi Illyoung, 

thanks a lot for your quick responses. I'm running it on a single linux server, not a cluster. We have ~1Tb memory on this single server, do you think is there an alternative way to run it in my case? 

Thanks, 
Shengwei

**Comment by iychoi** [comment]
In such case, you can setup the Hadoop cluster in a single node cluster mode (Pseudo cluster mode). Just make sure that your Hadoop utilizes all of your CPU cores and available RAM. To do so, you would need to configure several memory and container related parameters in YARN. And make sure your each of YARN containers and JVM in the container have at least 2GB of RAM.

**Comment by housw** [comment]
Hi Illyoung, 

thanks a lot, I will give it a try. 

Cheers, 
Shengwei

**Comment by ValerieLanglois** [comment]
Hi, 

I'm having a similar problem and looking for a solution 

I'm trying a run on 13 samples and get a similar error message (see below). What puzzle me is that I can run something else that I had run before (15 files, larger in GB but closer in diversity) and this run works perfectly but the new run won't 

Because I'm trying to run this on a server and I cannot access or change the hadoop configuration (and everyonte who can do so is in vacations) do you think it could be run on a laptop? (I highly doubt it could, but I simply have to ask) 



Here is the end of the log file,

2019-08-12 18:23:17,071 INFO mapreduce.Job: Counters: 18
        File System Counters
                FILE: Number of bytes read=607959373160
                FILE: Number of bytes written=781455130
                FILE: Number of read operations=0
                FILE: Number of large read operations=0
                FILE: Number of write operations=0
        Map-Reduce Framework
                Map input records=10790115
                Map output records=199
                Map output bytes=3262008
                Map output materialized bytes=3263998
                Input split bytes=27064
                Combine input records=199
                Combine output records=199
                Spilled Records=199
                Failed Shuffles=0
                Merged Map outputs=0
                GC time elapsed (ms)=23974
                Total committed heap usage (bytes)=2534867992576
        File Input Format Counters
                Bytes Read=4783483173
2019-08-12 18:23:17,184 ERROR preprocess.Preprocessor: java.lang.Exception: KmerHistogramBuilder Failed : 1
java.lang.Exception: KmerHistogramBuilder Failed : 1
        at libra.preprocess.Preprocessor.run(Preprocessor.java:107)
        at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:76)
        at libra.preprocess.Preprocessor.main(Preprocessor.java:47)
        at libra.Libra.main(Libra.java:74)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.hadoop.util.RunJar.run(RunJar.java:318)
        at org.apache.hadoop.util.RunJar.main(RunJar.java:232)


Thanks, 
Valerie

**Comment by iychoi** [comment]
Hi ValerieLanglois,

The log file doesn't contain details for the error. You would be able to find more detailed errors when setting log level to debug. 

Although I do not exactly know the reason, I can give you some points that are worth to be checked.
1. Input files. If input files are FASTQ files, check if they are in proper format. Previously, I saw a case someone had a wrong FASTQ file which has only 3 lines per record. Normal FASTQ files have 4 lines per record. I highly suspect this.
2. Use newer version of Libra. You can find newer versions of Libra at RELEASE page.

Let me know if you still have the same issue even after these. 

Also, yes, you can run Libra on your laptop. Check out below link.
https://hadoop.apache.org/docs/stable/hadoop-project-dist/hadoop-common/SingleCluster.html
I'm using a standalone operation for debugging Libra. But this setup will be really slow if you input more than 10MB samples.

Hope this helps.

**Comment by ValerieLanglois** [comment]
Hi Illyoung

The fastq files are real fastq files with 4 lines per read. I loaded the 1.2.8 version, we'll see if it works. So far the pipeline did not stop and it's been over 15 minutes now (around the time it took it to stop working before) and it now creates the kmerindex_temp folder that it did not create before so looking good! 

Thanks for your very quick response! I'll update with the final outcome.

**Comment by iychoi** [comment]
Great. If it stops, check out console logs. There must be some error messages other than what you had above.
And the version 1.2.8 does not construct k-mer histogram anymore. So it directly constructs k-mer index. That's why you see kmerindex_temp folder. But it doesn't mean you will succeed.
The k-mer histogram construction step in previous versions is a really quick task that just reads and checks histogram of k-mers of an input. So you got quick error return if there was a problem in the input. But with this version, it will take longer to hit the same point.

**Comment by ValerieLanglois** [comment]
Update : It worked! 

A thousand thanks for the help. 
Valerie

**Comment by iychoi** [comment]
Great!
