### ISSUE TITLE
Visualize the result

### ISSUE THREAD

**Issue by ValerieLanglois** [iychoi/libra#3]
Hi, 

I just finished my first run of libra (preprocess and core) and I got the .json and .score files.
At this point I have two questions, 
First I'm not familiar with these file types and I was wondering how you suggest to visualize the data. Ideally I'd like to know which software was used to create the circle Tara figure in the article but any other option is welcome!

Second, it seems that the software couldn't take my paired reeds (in separate files). 
Should I redo the run with the reads in interleaved files or is it possible to rerun the "core" line with an argument allowing it to process R1 and R2 as a single sample? 

Thanks!

**Comment by iychoi** [comment]
Hi,

For the first question, you will want a tool provided under the /tool dir.
https://github.com/iychoi/libra/blob/master/tools/gen_score_matrix.py#L73

You provide paths for the two files. By default, it will produce a similarity matrix which tells how close each of sample pairs are in a matrix. The matrix will be in a text form, so it's quite easy to copy paste to excel or other tools for post processing.

Once you get the matrix, my suggestion is using a viz tool like gephi (https://gephi.org/). The TARA figure was made using a custom Javascript tool. You can find some examples at my test website below. I cannot tell much about its source code as it's too specific to a Javascript framework. 
http://www2.cs.arizona.edu/~iychoi/viz/
http://www2.cs.arizona.edu/~iychoi/viz/tara/eb_static.html?min=0.3
http://www2.cs.arizona.edu/~iychoi/viz/tara/result.json

You would be able to reuse most of the code.


For the second question, if you want two separated files to be regarded as a single input, you will need to merge the files before running Libra. That'll be the easiest way that do not require code-level modification. Actually, we don't have feature for that.
